# THIS IS NOT HOW YOU SHOULD DO DEPLOYMENTS FOR YOUR ORGANIZATION
#
# First off, the sed stuff for modifying import maps is quite hacky and shouldn't
# be what you rely on.
#
# Secondly, each angular app should be in a separate repo and deployed separately, as
# explained in the README.md.
language: node_js
node_js:
  - "node"
script:
  - cd prefab-navbar && npm ci && npm run build:single-spa
  - cd ../prefab-home && npm ci && npm run build:single-spa
  - cd ../prefab-resume && npm ci && npm run build:single-spa
  - cd .. && mkdir static && cp -a prefab-navbar/dist prefab-home/dist prefab-resume/dist static
  - cp root-html-file/index.html static
  - sed -i 's/http:\/\/localhost:4201\/main/\/dist\/prefab-home\/main/g' static/index.html
  - sed -i 's/http:\/\/localhost:4202\/main/\/dist\/prefab-resume\/main/g' static/index.html
  - sed -i 's/http:\/\/localhost:4300\/main/\/dist\/prefab-navbar\/main/g' static/index.html
  - cp static/index.html static/200.html
  - echo "The static directory uploaded to surge:"
  - find static
deploy:
  provider: surge
  project: ./static/
  domain: coexisting-angular-microfrontends.surge.sh
  skip_cleanup: true